version: '3.4'

services:
  lumi-core-service:
    image: lumi-app:latest
    depends_on:
        - "lumi_db"
    build: .
    environment:
        ACCESS_TOKEN: "${ACCESS_TOKEN}"
        DOTNET_ENVIRONMENT: Docker-Production
    volumes:
      - ./applog:/app/AppLog
      - ./storage:/app/storage
    networks:
        - lumi-net-dev
  
  lumi_db:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
        POSTGRES_DB: "${DB_NAME}"
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks:
        - lumi-net-dev

  lumi-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    depends_on:
        - "lumi-core-service"
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: "${TUNNEL_TOKEN}"
    networks:
        - lumi-net-dev

networks:
 lumi-net-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
