//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.TelegramBot.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vanilla.TelegramBot.Resources.Texts.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        internal static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this project is to create a &quot;bridge&quot; between various creative personalities and the development of our creative sparks 🌟
        ///
        ///&lt;b&gt;Thank you&lt;/b&gt; for being with us ❤
        ///Also thank people who helped to develop this bot
        ///
        ///Created by a community member &lt;a href=&quot;https://t.me/include_anime&quot;&gt;Programmers &amp; Cookies&lt;/a&gt;
        ///You can contact the author here: &lt;a href=&quot;https://t.me/Yumikki&quot;&gt;@Yumikki&lt;/a&gt;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add own project.
        /// </summary>
        internal static string AddOwnProject {
            get {
                return ResourceManager.GetString("AddOwnProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        internal static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled the previous operation.
        /// </summary>
        internal static string CanceledOperation {
            get {
                return ResourceManager.GetString("CanceledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cannel {
            get {
                return ResourceManager.GetString("Cannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of your wonderful project?.
        /// </summary>
        internal static string CreateProjectInitMess {
            get {
                return ResourceManager.GetString("CreateProjectInitMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow Wow I see huge ambitions here, but alas, I can&apos;t fit them into one calf
        ///
        ///Describe your project more concisely. The maximum I can write is 4000 characters.
        /// </summary>
        internal static string CreateProkectDescriptionValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectDescriptionValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point to the links related to the project
        ///It can be a project development channel or its website
        ///
        ///❔ Separate several links with a comma
        ///&lt;i&gt;Example&lt;/i&gt;
        ///&lt;i&gt;https://t.me/include_anime, https://t.me/pandcgalaxy_bot&lt;/i&gt;.
        /// </summary>
        internal static string CreateProkectDevelopStatusMess {
            get {
                return ResourceManager.GetString("CreateProkectDevelopStatusMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops!
        ///
        ///You must choose the correct answer, not write to me!.
        /// </summary>
        internal static string CreateProkectDevelopStatusValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectDevelopStatusValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us more about it.
        /// </summary>
        internal static string CreateProkectNameAnswerMess {
            get {
                return ResourceManager.GetString("CreateProkectNameAnswerMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, the name of your project is as catchy as the names of some anime!
        ///
        ///But unfortunately, I cannot accept it
        ///The name must not exceed 64 characters.
        /// </summary>
        internal static string CreateProkectNameValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectNameValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;b&gt;I have successfully added your incredible project :3&lt;/b&gt;
        ///🔎 Now anyone can find it through inline search
        ///.
        /// </summary>
        internal static string CreateProkectSuccessMessage {
            get {
                return ResourceManager.GetString("CreateProkectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denial of access.
        /// </summary>
        internal static string DenialOfAccess {
            get {
                return ResourceManager.GetString("DenialOfAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed.
        /// </summary>
        internal static string Developed {
            get {
                return ResourceManager.GetString("Developed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find this project.
        /// </summary>
        internal static string FindThisProjectBtn {
            get {
                return ResourceManager.GetString("FindThisProjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In development.
        /// </summary>
        internal static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned to develop.
        /// </summary>
        internal static string PlannedToDevelop {
            get {
                return ResourceManager.GetString("PlannedToDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the completion project status.
        /// </summary>
        internal static string PoolDescription {
            get {
                return ResourceManager.GetString("PoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project has been deleted.
        /// </summary>
        internal static string ProjectHasBeenDeletedMes {
            get {
                return ResourceManager.GetString("ProjectHasBeenDeletedMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oooh
        ///
        ///An internal server error has occurred
        ///If the bot does not work correctly in the future, please contact {0}
        ///
        ///Error ID: &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Munch
        ///
        ///This is my message!!! 
        ///&lt;b&gt;I won&apos;t miss it&lt;/b&gt;
        ///
        ///Write it yourself.
        /// </summary>
        internal static string ThiIsMyMessageValidationMess {
            get {
                return ResourceManager.GetString("ThiIsMyMessageValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oooh
        ///
        ///How nice of you to send this, but it&apos;s not what I expected ;(.
        /// </summary>
        internal static string UnexpectedInputMess {
            get {
                return ResourceManager.GetString("UnexpectedInputMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateBtn {
            get {
                return ResourceManager.GetString("UpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow Wow I see huge ambitions here, but alas, I can&apos;t fit them into one calf
        ///
        ///Describe your project more concisely. The maximum I can write is 4000 characters.
        /// </summary>
        internal static string UpdateProjectDescriptionValidation {
            get {
                return ResourceManager.GetString("UpdateProjectDescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which value to replace?.
        /// </summary>
        internal static string UpdateProjectInitMessasge {
            get {
                return ResourceManager.GetString("UpdateProjectInitMessasge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow, the name of your project is as catchy as the names of some anime!
        ///
        ///But unfortunately, I cannot accept it
        ///The name must not exceed 64 characters.
        /// </summary>
        internal static string UpdateProjectNameValidation {
            get {
                return ResourceManager.GetString("UpdateProjectNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am waiting for a response to the survey.
        /// </summary>
        internal static string UpdateProjectPoolValidation {
            get {
                return ResourceManager.GetString("UpdateProjectPoolValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated!.
        /// </summary>
        internal static string UpdateProjectSuccess {
            get {
                return ResourceManager.GetString("UpdateProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About such
        ///You don&apos;t have any projects yet
        ///
        ///But you can add it!.
        /// </summary>
        internal static string UserDontHaveProjectsMess {
            get {
                return ResourceManager.GetString("UserDontHaveProjectsMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View own projects.
        /// </summary>
        internal static string ViewOwnProjects {
            get {
                return ResourceManager.GetString("ViewOwnProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}!
        ///I&apos;m glad to see you here
        ///I help you save and share your great projects, in a profitable way, anywhere
        ///
        ///🌟To add and manage your projects, open /menu
        ///
        ///🔎&lt;b&gt;To check people&apos;s projects, it is enough to type @{1} here, or in any other chat and channel&lt;/b&gt;
        ///
        ///I hope you like it here ❤️.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome: {0}!.
        /// </summary>
        internal static string WelcomeUserMessage {
            get {
                return ResourceManager.GetString("WelcomeUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What value to replace?.
        /// </summary>
        internal static string WhatValueToReplace {
            get {
                return ResourceManager.GetString("WhatValueToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry for the inconvenience. The bot actually resumed work.
        /// </summary>
        internal static string WorkRecoveryMes {
            get {
                return ResourceManager.GetString("WorkRecoveryMes", resourceCulture);
            }
        }
    }
}
