//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.TelegramBot.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ukrainian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ukrainian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vanilla.TelegramBot.Resources.Texts.Ukrainian", typeof(Ukrainian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закинуто.
        /// </summary>
        internal static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метою цього проекту є створення своєрідного &quot;мосту&quot; між творчими особистостями та розвиток наших творчих іскор 🌟.
        ///
        ///&lt;b&gt;Дякую&lt;/b&gt;, що ви з нами! ❤️
        ///Особлива подяка всім, хто допомагає розробляти цього бота.
        ///
        ///Створено учасником спільноти &lt;a href=&quot;https://t.me/include_anime&quot;&gt;Програмісти і печеньки&lt;/a&gt;
        ///Знайти розробників можете тут &lt;a href=&quot;https://t.me/LumiFanbase&quot;&gt;@LumiFanbase&lt;/a&gt;
        ///Сайт проекту: &lt;a href=&quot;{0}&quot;&gt;{1}&lt;/a&gt;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про мене.
        /// </summary>
        internal static string AboutKey {
            get {
                return ResourceManager.GetString("AboutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активовані бонуси ({0}) 🔭.
        /// </summary>
        internal static string ActivatedBonusesLabel {
            get {
                return ResourceManager.GetString("ActivatedBonusesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати власний проект.
        /// </summary>
        internal static string AddOwnProject {
            get {
                return ResourceManager.GetString("AddOwnProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати проект.
        /// </summary>
        internal static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернутись.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої бонуси.
        /// </summary>
        internal static string BonusSytemBtn {
            get {
                return ResourceManager.GetString("BonusSytemBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередню дію скасовано.
        /// </summary>
        internal static string CanceledOperation {
            get {
                return ResourceManager.GetString("CanceledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        internal static string Cannel {
            get {
                return ResourceManager.GetString("Cannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда &lt;i&gt;{0}&lt;/i&gt; не розпізнана.
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити профіль.
        /// </summary>
        internal static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити проект.
        /// </summary>
        internal static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як називається твій проект?.
        /// </summary>
        internal static string CreateProjectInitMess {
            get {
                return ResourceManager.GetString("CreateProjectInitMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воу-воу! Я бачу, у тебе великі амбіції, але, на жаль, не зможу вмістити все це в одному повідомленні.
        ///
        ///Будь ласка, опиши свій проект більш стисло. Максимально можна вмістити лише 4000 знаків..
        /// </summary>
        internal static string CreateProkectDescriptionValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectDescriptionValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть на пов&apos;язані з проектом посилання
        ///Це може бути як канал розвитку проекту, так і саме посилання на проект
        ///
        ///❔ Для введення більше ніж одного посилання, розділи їх комою (,)
        ///&lt;i&gt;Приклад&lt;/i&gt;
        ///&lt;i&gt;https://t.me/include_anime, https://t.me/pandcgalaxy_bot&lt;/i&gt;.
        /// </summary>
        internal static string CreateProkectDevelopStatusMess {
            get {
                return ResourceManager.GetString("CreateProkectDevelopStatusMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ой!
        ///
        ///Ви повинні обрати одну з відповідей, а не писати мені!.
        /// </summary>
        internal static string CreateProkectDevelopStatusValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectDevelopStatusValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розкажи про цей проект докладніше.
        /// </summary>
        internal static string CreateProkectNameAnswerMess {
            get {
                return ResourceManager.GetString("CreateProkectNameAnswerMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ого, ваша назва проекту така довга, як назви деяких аніме! 😄
        ///
        ///Але, на жаль, я не можу це прийняти. Назва не повинна перевищувати 64 символи..
        /// </summary>
        internal static string CreateProkectNameValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectNameValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;b&gt;Я успішно зберегла ваш неймовірний проект&lt;/b&gt;
        ///
        ///🔎 Тепер будь-хто зможе його знайти через inline пошук
        ///.
        /// </summary>
        internal static string CreateProkectSuccessMessage {
            get {
                return ResourceManager.GetString("CreateProkectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відказано у доступі.
        /// </summary>
        internal static string DenialOfAccess {
            get {
                return ResourceManager.GetString("DenialOfAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розроблено.
        /// </summary>
        internal static string Developed {
            get {
                return ResourceManager.GetString("Developed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Знайти через inline пошук.
        /// </summary>
        internal static string FindThisProjectBtn {
            get {
                return ResourceManager.GetString("FindThisProjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заморожено.
        /// </summary>
        internal static string Frozen {
            get {
                return ResourceManager.GetString("Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отримати бонус.
        /// </summary>
        internal static string GetBonus {
            get {
                return ResourceManager.GetString("GetBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✨ Приймаю замовлення.
        /// </summary>
        internal static string IAcceptOrders {
            get {
                return ResourceManager.GetString("IAcceptOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зображення.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У розробці.
        /// </summary>
        internal static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готовність до співпраці.
        /// </summary>
        internal static string IsRedyToWork {
            get {
                return ResourceManager.GetString("IsRedyToWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання &lt;i&gt;{0}&lt;/i&gt; є не вірним. Спробуй ще раз.
        /// </summary>
        internal static string LinksNotCorrect {
            get {
                return ResourceManager.GetString("LinksNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відкрити меню.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть дію з меню.
        /// </summary>
        internal static string MainMenuSendMes {
            get {
                return ResourceManager.GetString("MainMenuSendMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мій профіль.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити профіль.
        /// </summary>
        internal static string MyProfileUpdate {
            get {
                return ResourceManager.GetString("MyProfileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нікнейм.
        /// </summary>
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пропустити.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В планах.
        /// </summary>
        internal static string PlannedToDevelop {
            get {
                return ResourceManager.GetString("PlannedToDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На якому етапі розробки знаходиться ваш проект?.
        /// </summary>
        internal static string PoolDescription {
            get {
                return ResourceManager.GetString("PoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект було видалено.
        /// </summary>
        internal static string ProjectHasBeenDeletedMes {
            get {
                return ResourceManager.GetString("ProjectHasBeenDeletedMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перезапустити Lumi.
        /// </summary>
        internal static string ReloadUserContext {
            get {
                return ResourceManager.GetString("ReloadUserContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти проект.
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук проектів.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Ой-йой.. 500&lt;/b&gt;
        ///Виникла внутрішня помилка серверу
        ///
        ///Якщо Лумі, надалі, не працюватиме належним чином, повідомте про це у &lt;a href=&quot;https://t.me/LumiFanbase&quot;&gt;Lumi fanbase&lt;/a&gt;
        ///
        ///Error ID: &lt;code&gt;{1}&lt;/code&gt;.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Витратити.
        /// </summary>
        internal static string Spend {
            get {
                return ResourceManager.GetString("Spend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Етап розробки.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отакої
        ///
        ///Виглядає як моє повідомлення!! 
        ///&lt;b&gt;Не можу його прийняти&lt;/b&gt;.
        /// </summary>
        internal static string ThiIsMyMessageValidationMess {
            get {
                return ResourceManager.GetString("ThiIsMyMessageValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця функція лише для зареєстрованих користувачів..
        /// </summary>
        internal static string ThisFeatureIsOnlyForRegisteredUsers {
            get {
                return ResourceManager.GetString("ThisFeatureIsOnlyForRegisteredUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вірно.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректний ввід.
        /// </summary>
        internal static string UnexpectedInput {
            get {
                return ResourceManager.GetString("UnexpectedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ООО
        ///
        ///Як мило з вашого боку, що прислали це повідомлення, але воно не є тим чого я очікувала 😑
        ///
        ///Повторіть спробу ще раз.
        /// </summary>
        internal static string UnexpectedInputMess {
            get {
                return ResourceManager.GetString("UnexpectedInputMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновити.
        /// </summary>
        internal static string UpdateBtn {
            get {
                return ResourceManager.GetString("UpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воу-воу! Я бачу, у тебе великі амбіції, але, на жаль, не зможу вмістити все це в одному повідомленні.
        ///
        ///Будь ласка, опиши свій проект більш стисло. Максимально можна вмістити лише 4000 знаків..
        /// </summary>
        internal static string UpdateProjectDescriptionValidation {
            get {
                return ResourceManager.GetString("UpdateProjectDescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Що ти хочеш змінити?.
        /// </summary>
        internal static string UpdateProjectInitMessasge {
            get {
                return ResourceManager.GetString("UpdateProjectInitMessasge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ого, ваша назва проекту така довга, як назви деяких аніме! 😄
        ///
        ///Але, на жаль, я не можу це прийняти. Назва не повинна перевищувати 64 символи..
        /// </summary>
        internal static string UpdateProjectNameValidation {
            get {
                return ResourceManager.GetString("UpdateProjectNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я очікую відповіді на опитування.
        /// </summary>
        internal static string UpdateProjectPoolValidation {
            get {
                return ResourceManager.GetString("UpdateProjectPoolValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновлено!.
        /// </summary>
        internal static string UpdateProjectSuccess {
            get {
                return ResourceManager.GetString("UpdateProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У мене ще немає записів про твої проекти, але ми можемо додати їх прямо зараз!.
        /// </summary>
        internal static string UserDontHaveProjectsMess {
            get {
                return ResourceManager.GetString("UserDontHaveProjectsMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої проекти.
        /// </summary>
        internal static string ViewOwnProjects {
            get {
                return ResourceManager.GetString("ViewOwnProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я тут, щоб допомогти тобі поширювати свої проекти де завгодно та з ким завгодно, і знайти однодумців, які підтримають тебе, і твої ідеї! 🎨✨
        ///
        ///🌟 Щоб розпочати нашу подорож, просто відкрий /menu, або скористайся кнопками нижче.
        ///
        ///💡&lt;b&gt;Бажаєш дізнатися, що створили інші?&lt;/b&gt; Легко! 
        ///
        ///🔍Введи @{1} тут або в будь-якому іншому чаті чи каналі. Надихайся ідеями наших учасників і відкривай для себе нові проекти! .
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт
        ///
        ///Я безмежно рада бачити тебе тут! ❤️.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я тут, щоб допомогти тобі поширювати свої проекти де завгодно та з ким завгодно, і знайти однодумців, які підтримають тебе, і твої ідеї! 🎨✨
        ///
        ///🌟 Перед початком нашої подорожі, тобі необхідно створити профіль!
        ///
        ///💡&lt;b&gt;Бажаєш дізнатися, що створили інші?&lt;/b&gt; Легко! 
        ///
        ///🔍Введи @{1} тут або в будь-якому іншому чаті чи каналі. Надихайся ідеями наших учасників і відкривай для себе нові проекти!.
        /// </summary>
        internal static string WelcomeNewUser {
            get {
                return ResourceManager.GetString("WelcomeNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привіт {0}!
        ///
        ///Я безмежно рада бачити тебе тут! ❤️.
        /// </summary>
        internal static string WelcomeUserMessage {
            get {
                return ResourceManager.GetString("WelcomeUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введи нове значення.
        /// </summary>
        internal static string WhatValueToReplace {
            get {
                return ResourceManager.GetString("WhatValueToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибачте за незручності. Бот відновив свою роботу.
        /// </summary>
        internal static string WorkRecoveryMes {
            get {
                return ResourceManager.GetString("WorkRecoveryMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
