//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanilla.TelegramBot.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ukrainian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ukrainian() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vanilla.TelegramBot.Resources.Texts.Ukrainian", typeof(Ukrainian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abandoned.
        /// </summary>
        internal static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The purpose of this project is to create a &quot;bridge&quot; between various creative personalities and the development of our creative sparks 🌟
        ///
        ///&lt;b&gt;Thank you&lt;/b&gt; for being with us ❤
        ///Also thank people who helped to develop this bot
        ///
        ///Created by a community member &lt;a href=&quot;https://t.me/include_anime&quot;&gt;Programmers &amp; Cookies&lt;/a&gt;
        ///You can contact the author here: &lt;a href=&quot;https://t.me/Yumikki&quot;&gt;@Yumikki&lt;/a&gt;.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add own project.
        /// </summary>
        internal static string AddOwnProject {
            get {
                return ResourceManager.GetString("AddOwnProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add project.
        /// </summary>
        internal static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Canceled the previous operation.
        /// </summary>
        internal static string CanceledOperation {
            get {
                return ResourceManager.GetString("CanceledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        internal static string Cannel {
            get {
                return ResourceManager.GetString("Cannel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu What is the name of your wonderful project?.
        /// </summary>
        internal static string CreateProjectInitMess {
            get {
                return ResourceManager.GetString("CreateProjectInitMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wow Wow I see huge ambitions here, but alas, I can&apos;t fit them into one calf
        ///
        ///Describe your project more concisely. The maximum I can write is 4000 characters.
        /// </summary>
        internal static string CreateProkectDescriptionValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectDescriptionValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Point to the links related to the project
        ///It can be a project development channel or its website
        ///
        ///❔ Separate several links with a comma
        ///&lt;i&gt;Example&lt;/i&gt;
        ///&lt;i&gt;https://t.me/include_anime, https://t.me/pandcgalaxy_bot&lt;/i&gt;.
        /// </summary>
        internal static string CreateProkectDevelopStatusMess {
            get {
                return ResourceManager.GetString("CreateProkectDevelopStatusMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Whoops!
        ///
        ///You must choose the correct answer, not write to me!.
        /// </summary>
        internal static string CreateProkectDevelopStatusValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectDevelopStatusValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tell us more about it.
        /// </summary>
        internal static string CreateProkectNameAnswerMess {
            get {
                return ResourceManager.GetString("CreateProkectNameAnswerMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wow, the name of your project is as catchy as the names of some anime!
        ///
        ///But unfortunately, I cannot accept it
        ///The name must not exceed 64 characters.
        /// </summary>
        internal static string CreateProkectNameValidationMess {
            get {
                return ResourceManager.GetString("CreateProkectNameValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 
        ///
        ///&lt;b&gt;I have successfully added your incredible project :3&lt;/b&gt;
        ///🔎 Now anyone can find it through inline search
        ///.
        /// </summary>
        internal static string CreateProkectSuccessMessage {
            get {
                return ResourceManager.GetString("CreateProkectSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        internal static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Developed.
        /// </summary>
        internal static string Developed {
            get {
                return ResourceManager.GetString("Developed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Find this project.
        /// </summary>
        internal static string FindThisProjectBtn {
            get {
                return ResourceManager.GetString("FindThisProjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In development.
        /// </summary>
        internal static string InDevelopment {
            get {
                return ResourceManager.GetString("InDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Main menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Planned to develop.
        /// </summary>
        internal static string PlannedToDevelop {
            get {
                return ResourceManager.GetString("PlannedToDevelop", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select the completion project status.
        /// </summary>
        internal static string PoolDescription {
            get {
                return ResourceManager.GetString("PoolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oooh
        ///
        ///An internal server error has occurred
        ///If the bot does not work correctly in the future, please contact {0}
        ///
        ///Error ID: &lt;b&gt;{1}&lt;/b&gt;.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Munch
        ///
        ///This is my message!!! 
        ///&lt;b&gt;I won&apos;t miss it&lt;/b&gt;
        ///
        ///Write it yourself.
        /// </summary>
        internal static string ThiIsMyMessageValidationMess {
            get {
                return ResourceManager.GetString("ThiIsMyMessageValidationMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oooh
        ///
        ///How nice of you to send this, but it&apos;s not what I expected ;(.
        /// </summary>
        internal static string UnexpectedInputMess {
            get {
                return ResourceManager.GetString("UnexpectedInputMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Update.
        /// </summary>
        internal static string UpdateBtn {
            get {
                return ResourceManager.GetString("UpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wow Wow I see huge ambitions here, but alas, I can&apos;t fit them into one calf
        ///
        ///Describe your project more concisely. The maximum I can write is 4000 characters.
        /// </summary>
        internal static string UpdateProjectDescriptionValidation {
            get {
                return ResourceManager.GetString("UpdateProjectDescriptionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Which value to replace?.
        /// </summary>
        internal static string UpdateProjectInitMessasge {
            get {
                return ResourceManager.GetString("UpdateProjectInitMessasge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wow, the name of your project is as catchy as the names of some anime!
        ///
        ///But unfortunately, I cannot accept it
        ///The name must not exceed 64 characters.
        /// </summary>
        internal static string UpdateProjectNameValidation {
            get {
                return ResourceManager.GetString("UpdateProjectNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu I am waiting for a response to the survey.
        /// </summary>
        internal static string UpdateProjectPoolValidation {
            get {
                return ResourceManager.GetString("UpdateProjectPoolValidation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully updated!.
        /// </summary>
        internal static string UpdateProjectSuccess {
            get {
                return ResourceManager.GetString("UpdateProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu About such
        ///You don&apos;t have any projects yet
        ///
        ///But you can add it!.
        /// </summary>
        internal static string UserDontHaveProjectsMess {
            get {
                return ResourceManager.GetString("UserDontHaveProjectsMess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View own projects.
        /// </summary>
        internal static string ViewOwnProjects {
            get {
                return ResourceManager.GetString("ViewOwnProjects", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hi {0}!
        ///I&apos;m glad to see you here
        ///I help you save and share your great projects, in a profitable way, anywhere
        ///
        ///🌟To add and manage your projects, open /menu
        ///
        ///🔎&lt;b&gt;To check people&apos;s projects, it is enough to type @{1} here, or in any other chat and channel&lt;/b&gt;
        ///
        ///I hope you like it here ❤️.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome: {0}!.
        /// </summary>
        internal static string WelcomeUserMessage {
            get {
                return ResourceManager.GetString("WelcomeUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu What value to replace?.
        /// </summary>
        internal static string WhatValueToReplace {
            get {
                return ResourceManager.GetString("WhatValueToReplace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sorry for the inconvenience. The bot actually resumed work.
        /// </summary>
        internal static string WorkRecoveryMes {
            get {
                return ResourceManager.GetString("WorkRecoveryMes", resourceCulture);
            }
        }
    }
}
