receivers:
  otlp:
    protocols:
      http:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  resource: # Resource spec https://opentelemetry.io/docs/specs/semconv/resource/
    attributes:
      - action: insert
        key: loki.format
        value: raw
      - action: insert
        key: loki.resource.labels
        value: service.name, app, runtime
  
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  prometheus: # metrics
    endpoint: "0.0.0.0:9090"
    namespace: demo
    send_timestamps: true
    resource_to_telemetry_conversion:
      enabled: true
    const_labels:
      exported: "collector"
  
  # otlp/tempo:
  #   endpoint: tempo:4317
  #   tls:
  #     insecure: true

  # otlp/aspire:
  #   endpoint: aspire-dashboard:18889
  #   tls:
  #     insecure: true

  otlp/jager:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
    
    traces:
      receivers: [ otlp ]
      # processors: [ batch ]
      exporters: [ otlp/jager ]
    
    logs:
      receivers: [ otlp ]
      processors: [ batch, resource ]
      exporters: [ loki ]